# MySQL - CREATE USER user PASSWORD '!@#' SUPERUSER;
spring.datasource.url=jdbc:mysql://example-db.rds.amazonaws.com:3306/example?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=asac
spring.datasource.password=1234
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false